# Generated by Django 5.2.17 on 2026-09-28 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(unique=True)),
                ('provider_payment_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('pending_outcome', models.CharField(blank=True, choices=[('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mockpay_charges',
            },
        ),
    ]
