# Generated by Django 5.2.17 on 2026-09-28 17:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text="In paise; always the booking's amount.")),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('method', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
                ('refund_status', models.CharField(blank=True, choices=[('PENDING', 'Refund owed'), ('PROCESSED', 'Refunded')], default='', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('REJECTED', 'Rejected (needs review)')], max_length=16)),
                ('outcome', models.CharField(blank=True, default='', max_length=48)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['created_at'], name='payments_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'SUCCESS'))), fields=('booking',), name='payments_one_live_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='payments_provider_payment_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESS', 'FAILED'])), name='payments_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PENDING'), ('completed_at__isnull', False), _connector='OR'), name='payments_completed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refund_status', ''), models.Q(('refund_status__in', ['PENDING', 'PROCESSED']), ('status', 'SUCCESS')), _connector='OR'), name='payments_refund_only_when_paid'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='webhook_events_uniq'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PROCESSED', 'IGNORED', 'REJECTED'])), name='webhook_events_status_valid'),
        ),
    ]
