# Generated by Django 5.2.17 on 2026-09-28 17:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_at', models.DateTimeField()),
                ('amount', models.IntegerField(help_text='In paise.')),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('status_reason', models.CharField(blank=True, choices=[('PAYMENT_DECLINED', 'Payment declined'), ('PAYMENT_TIMEOUT', 'Not paid before the hold expired'), ('USER_CANCELLED', 'Cancelled by the patient'), ('ADMIN_CANCELLED', 'Cancelled by EVE operations')], default='', max_length=24)),
                ('hold_expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('offering', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.offering')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='', max_length=16)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('reason', models.CharField(blank=True, choices=[('PAYMENT_DECLINED', 'Payment declined'), ('PAYMENT_TIMEOUT', 'Not paid before the hold expired'), ('USER_CANCELLED', 'Cancelled by the patient'), ('ADMIN_CANCELLED', 'Cancelled by EVE operations')], default='', max_length=24)),
                ('actor_type', models.CharField(choices=[('USER', 'Patient'), ('ADMIN', 'Administrator'), ('SYSTEM', 'System'), ('PROVIDER', 'Payment provider')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_status_events',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='bookings_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['offering', 'appointment_at'], name='bookings_offering_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['hold_expires_at'], name='bookings_pending_hold_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'CONFIRMED'))), fields=('user', 'offering', 'appointment_at'), name='bookings_one_active_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bookings_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED'])), name='bookings_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status_reason__in', ['PAYMENT_DECLINED', 'PAYMENT_TIMEOUT', 'USER_CANCELLED', 'ADMIN_CANCELLED', ''])), name='bookings_status_reason_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='bookings_confirmed_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='bookings_cancelled_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='bookingstatusevent',
            index=models.Index(fields=['booking', 'created_at'], name='booking_events_booking_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED'])), name='booking_events_to_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='bookingstatusevent',
            constraint=models.CheckConstraint(condition=models.Q(('actor_type__in', ['USER', 'ADMIN', 'SYSTEM', 'PROVIDER'])), name='booking_events_actor_type_valid'),
        ),
    ]
