# Generated by Django 5.2.17 on 2026-09-28 16:46

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCentre',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address_line', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'diagnostic_centres',
                'ordering': ('name', 'id'),
                'indexes': [models.Index(django.db.models.functions.text.Lower('city'), condition=models.Q(('is_active', True)), name='diagnostic_centres_city_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('city'), name='diagnostic_centres_name_city_uniq'), models.CheckConstraint(condition=models.Q(('pincode__regex', '^[1-9][0-9]{5}$')), name='diagnostic_centres_pincode_format'), models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='diagnostic_centres_hours_valid'), models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='diagnostic_centres_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='diagnostic_centres_longitude_range')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PATHOLOGY', 'Pathology'), ('RADIOLOGY', 'Radiology'), ('CARDIOLOGY', 'Cardiology'), ('OTHER', 'Other')], max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('preparation', models.TextField(blank=True, default='', help_text='Instructions for the patient, e.g. fasting.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'diagnostic_tests',
                'ordering': ('name', 'id'),
                'constraints': [models.UniqueConstraint(fields=('code',), name='diagnostic_tests_code_uniq'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9_]{2,32}$')), name='diagnostic_tests_code_format'), models.CheckConstraint(condition=models.Q(('category__in', ['PATHOLOGY', 'RADIOLOGY', 'CARDIOLOGY', 'OTHER'])), name='diagnostic_tests_category_valid')],
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(help_text='In paise: 150000 is ₹1,500.00.')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('centre', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.diagnosticcentre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='catalog.diagnostictest')),
            ],
            options={
                'db_table': 'offerings',
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['test', 'price'], name='offerings_test_price_idx')],
                'constraints': [models.UniqueConstraint(fields=('centre', 'test'), name='offerings_centre_test_uniq'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='offerings_price_positive'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='offerings_currency_format')],
            },
        ),
    ]
