# Generated by Django 5.2.17 on 2026-09-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='slot_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='offering',
            constraint=models.CheckConstraint(condition=models.Q(('slot_capacity__isnull', True), ('slot_capacity__gt', 0), _connector='OR'), name='offerings_slot_capacity_positive'),
        ),
    ]
